

driver: {
  shape: sql_table
  dref : string {constraint: primary_key}
  forename: string
  surname: string
  dob: date
  nationality: string
  code: string
  number: int
}

style: {
  fill: transparent
}
